const express = require("express")
const usuarioRoutes = require("./usuario.routes")
const clienteRoutes = require("./cliente.routes")
const funcionarioRoutes = require("./funcionario.routes")
const petRoutes = require("./pet.routes")
const categoriaServicoRoutes = require("./categoriaServico.routes")
const servicoRoutes = require("./servico.routes")
const agendamentoRoutes = require("./agendamento.routes")
const categoriaProdutoRoutes = require("./categoriaProduto.routes")
const fornecedorRoutes = require("./fornecedor.routes")
const produtoRoutes = require("./produto.routes")
const vendaRoutes = require("./venda.routes")
const tarefaRoutes = require("./tarefa.routes")
const authRoutes = require("./auth.routes")

const router = express.Router()

router.use("/auth", authRoutes)
router.use("/usuarios", usuarioRoutes)
router.use("/clientes", clienteRoutes)
router.use("/funcionarios", funcionarioRoutes)
router.use("/pets", petRoutes)
router.use("/categorias-servico", categoriaServicoRoutes)
router.use("/servicos", servicoRoutes)
router.use("/agendamentos", agendamentoRoutes)
router.use("/categorias-produto", categoriaProdutoRoutes)
router.use("/fornecedores", fornecedorRoutes)
router.use("/produtos", produtoRoutes)
router.use("/vendas", vendaRoutes)
router.use("/tarefas", tarefaRoutes)

module.exports = router
